In [1]:
import torch

在官方tutorial以及《动手学》的书中，torch.empty()生成的张量中并不全为0，按官方说法是，"values that were in the allocated memory"

In [3]:
x = torch.empty(5, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.rand()随机初始化，其中的值服从U(0,1)

torch.randn()生成服从N(0,1)的值

In [4]:
x = torch.rand(3, 4)
print(x)

tensor([[0.3769, 0.3294, 0.2281, 0.8311],
        [0.5279, 0.5819, 0.0604, 0.4873],
        [0.2259, 0.7543, 0.8833, 0.4825]])


In [5]:
x = torch.zeros(2, 3, dtype=torch.long)
y = torch.ones(2, 2, dtype=torch.float)
print(x, y)

tensor([[0, 0, 0],
        [0, 0, 0]]) tensor([[1., 1.],
        [1., 1.]])


torch.Tensor.new_ones()生成新的张量，需要指定新张量的size，默认继承torch.dtype以及torch.device

In [8]:
z = y.new_ones(3)
print(z)

tensor([1., 1., 1.])


In [7]:
print(x.size())
print(x.shape)

torch.Size([2, 3])
torch.Size([2, 3])


pytorch中加法的两种形式

torch.add(input, other, out=None)

$out = input + other$

注：out需要提前声明，但似乎并不在意out原本的size是什么样的？见下方代码

In [9]:
x = torch.ones(3, 4)
y = torch.rand(3, 4)

print(x + y)
print(torch.add(x, y))

tensor([[1.8194, 1.9275, 1.7167, 1.8103],
        [1.7587, 1.0751, 1.2124, 1.3455],
        [1.8625, 1.9173, 1.1703, 1.0286]])
tensor([[1.8194, 1.9275, 1.7167, 1.8103],
        [1.7587, 1.0751, 1.2124, 1.3455],
        [1.8625, 1.9173, 1.1703, 1.0286]])


这里result本来的size并不和x及y相同

In [11]:
result = torch.empty(1, 2)
torch.add(x, y, out=result)

tensor([[1.8194, 1.9275, 1.7167, 1.8103],
        [1.7587, 1.0751, 1.2124, 1.3455],
        [1.8625, 1.9173, 1.1703, 1.0286]])

In [12]:
result

tensor([[1.8194, 1.9275, 1.7167, 1.8103],
        [1.7587, 1.0751, 1.2124, 1.3455],
        [1.8625, 1.9173, 1.1703, 1.0286]])

注：PyTorch操作inplace版本都有后缀_, 例如x.copy_(y), x.t_()

In [13]:
y.add_(x)
print(y)

tensor([[1.8194, 1.9275, 1.7167, 1.8103],
        [1.7587, 1.0751, 1.2124, 1.3455],
        [1.8625, 1.9173, 1.1703, 1.0286]])


pytorch索引操作不创建新内存。索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。

In [14]:
x = y[0, :]
x += 1

print(x)
print(y[0, :])

tensor([2.8194, 2.9275, 2.7167, 2.8103])
tensor([2.8194, 2.9275, 2.7167, 2.8103])


注：torch.Tensor.view()同样也是共享内存的

In [15]:
y_1 = y.view(12)
y_2 = y.view(2, -1)

print(y_1.size(), y_2.size())

torch.Size([12]) torch.Size([2, 6])


为了解决共享内存的问题，建议使用torch.Tensor.clone().view()

使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。

In [16]:
y_cp = y.clone().view(12)

y -= 1
print(y_cp)
print(y)

tensor([2.8194, 2.9275, 2.7167, 2.8103, 1.7587, 1.0751, 1.2124, 1.3455, 1.8625,
        1.9173, 1.1703, 1.0286])
tensor([[1.8194, 1.9275, 1.7167, 1.8103],
        [0.7587, 0.0751, 0.2124, 0.3455],
        [0.8625, 0.9173, 0.1703, 0.0286]])


In [17]:
x = torch.randn(1)

print(x)
print(x.item())

tensor([1.9088])
1.908822774887085
